#!/usr/bin/python
# --------------- #
# setgit.py
#
# Script to manage multiple global gitconfigs
# 
#
# To load .gitconfig-this to .gitconfig it run:
# setgit -l this
# 
# 
# Author: Jeffrey Stone <thejeffreystone@gmail.com>
# --------------- #
__author__ = 'Jeffrey Stone <thejeffreystone@gmail.com>'

# modules
import sys, os, shutil, argparse


# Main Program 
def main():
	# Create Parser that will read command line input
	parser = argparse.ArgumentParser(description="create .gitconfig from a source file .gitconfig-source")
	parser.add_argument("-l", "--load", action="store_true",
                    help="load git config from source")
	parser.add_argument("source",
                    help="the source identifier")
	args = parser.parse_args()


	if args.load:
		if os.path.isfile(os.environ['HOME'] + '/.gitconfig-' + args.source ):
			shutil.copyfile(os.environ['HOME'] + '/.gitconfig-' + args.source, os.environ['HOME'] + '/.gitconfig' )
		else:
			print "I could not find a source file " + os.environ['HOME'] + "/.gitconfig-" + args.source
			



# Let's run this thing.
if __name__ == '__main__':
	main()
